locals {
  config           = yamldecode(file("${path.module}/../../config.yaml"))
  autostop_enabled = local.config.auto_stop.enabled
  timezone         = local.config.auto_stop.timezone
  schedule         = local.config.auto_stop.schedule

  # ── Stop script: deletes the cluster to stop billing ─────────────────────
  # Equivalent of AKS Stop-AzAksCluster.
  # WARNING: this destroys all running pods. Persistent volumes are preserved
  # if you recreate with the same name and re-attach them.
  stop_script = <<-EOF
    #!/usr/bin/env bash
    # Auto-generated by Terraform — do not edit manually
    # Timezone: ${local.timezone}
    set -euo pipefail
    export CIVO_TOKEN="Ensure you use a secure method (e.g., GitHub Secrets)"
    echo "[$(date)] Stopping (deleting) cluster ${var.cluster_name} in ${var.region}..."
    civo kubernetes remove ${var.cluster_name} --region ${var.region} --yes
    echo "[$(date)] Cluster deleted."
  EOF

  # ── Start script: recreates the cluster ──────────────────────────────────
  # Equivalent of AKS Start-AzAksCluster.
  # Kubeconfig is refreshed automatically; DNS points to new node IP.
  start_script = <<-EOF
    #!/usr/bin/env bash
    # Auto-generated by Terraform — do not edit manually
    # Timezone: ${local.timezone}
    set -euo pipefail
    export CIVO_TOKEN="Ensure you use a secure method (e.g., GitHub Secrets)"
    echo "[$(date)] Starting (recreating) cluster ${var.cluster_name} in ${var.region}..."
    civo kubernetes create ${var.cluster_name} \
      --size ${var.node_size} \
      --nodes ${var.node_count} \
      --region ${var.region} \
      --wait
    civo kubernetes config ${var.cluster_name} --region ${var.region} --save --merge
    echo "[$(date)] Cluster ready."
  EOF
}
