#!/usr/bin/env bash
# Auto-generated by Terraform — do not edit manually
# Timezone: America/New_York
set -euo pipefail
export CIVO_TOKEN="Ensure you use a secure method (e.g., GitHub Secrets)"
echo "[$(date)] Starting (recreating) cluster civo-secops-gitops-lab in NYC1..."
civo kubernetes create civo-secops-gitops-lab \
  --size g4s.kube.medium \
  --nodes 1 \
  --region NYC1 \
  --wait
civo kubernetes config civo-secops-gitops-lab --region NYC1 --save --merge
echo "[$(date)] Cluster ready."
