#!/usr/bin/env bash
# Auto-generated by Terraform — do not edit manually
# Timezone: America/New_York
set -euo pipefail
export CIVO_TOKEN="Ensure you use a secure method (e.g., GitHub Secrets)"
echo "[$(date)] Stopping (deleting) cluster civo-secops-gitops-lab in NYC1..."
civo kubernetes remove civo-secops-gitops-lab --region NYC1 --yes
echo "[$(date)] Cluster deleted."
